### ISSUE TITLE
Simple result 

### ISSUE THREAD

**Issue by gvetaw** [ASU-CompMethodsPhysics-PHY494/final-stern-gerlach-simulation#10]
@ion201 @andrewdurkiewicz  Nate could you explain what parameters were changed for the "simple result" so that we can talk about it in the conclusion section of the poster. Thank you.

**Comment by ion201** [comment]
The simple result removes the y-dependence of the magnetic field and purely uses z (B0+alpha*z). This is the term that creates creates a dependence relationship between the two waves.
