### ISSUE TITLE
How to do the wave packet

### ISSUE THREAD

**Issue by andrewdurkiewicz** [ASU-CompMethodsPhysics-PHY494/final-stern-gerlach-simulation#2]
@ASU-CompMethodsPhysics-PHY494/stern-gerlach-simulation Hey guys, so I am a bit confused as far as to what we will be calculating and setting for the wave packet portion. It seems we will be solving the time dependent Schrodinger equation. So I would think we vary time. But why cant we solve the time independent and use position like in classical?

**Comment by orbeckst** [comment]
See also #4 .
