### ISSUE TITLE
Introduction for poster

### ISSUE THREAD

**Issue by gvetaw** [ASU-CompMethodsPhysics-PHY494/final-stern-gerlach-simulation#9]
@ion201 @andrewdurkiewicz  Here is a great start for the introduction for the poster. Feel free to add or subtract. 

The Stern-Gerlach experiment demonstrates that when a beam of atoms passes through an inhomogeneous (nonuniform) magnetic field the beam splits into two discrete states being spin up or spin down. This effect is purely quantum mechanical and is owing to an inherent property possessed by particles called Spin angular momentum. Spin is an intrinsic degree of freedom that is separate from moving particles’ spatial degrees of freedom.

**Comment by gvetaw** [comment]
@andrewdurkiewicz @ion201 please send any resources to be cited so that I can add it to the poster. For the introduction I used Zettili.

**Comment by andrewdurkiewicz** [comment]
those two i sent you should be sources.

**Comment by gvetaw** [comment]
Are we settling on the Hamiltonian on the wikipage and states because I am going to add it to the methods section.

**Comment by andrewdurkiewicz** [comment]
I say we should, I think we could go about this project in many different ways. And that way does a wonderfully smart thing where they set the origin to the electron. Its incredibly smart when you think about it. But go for it if you want. But to me, that is a sign that you are considering doing it my way?

**Comment by gvetaw** [comment]
Did @ion201 just use the Crank-Nicolson method for the project?

**Comment by andrewdurkiewicz** [comment]
first thing, do we owe you $ for the poster? We both agreed to pitch in. second. you might want to print things out but not post them. Until we know for sure that the code works then we should wait. Nate is finding issues with both of our hamiltonian. They both seem to be unstable in time.

**Comment by gvetaw** [comment]
The gaussian in the quantum test file can only be a fuction of x or p but it can't be a function of both because it states that the particle is strongly peaked around so position or momentum in one of the spaces. To get the gaussian in position space just do a simple inverse fourier transform "np.fft.ifft"

**Comment by gvetaw** [comment]
What I am going to do is start the poster in send it to you and you can decided if you want to print it out as a whole or do individual papers since it was your proposed project.

**Comment by gvetaw** [comment]
The introduction of the poster doesn't have any equation or methods that can be done today. There are two methods section on the poster: method for the theory and method for the algorithm. The theory section can be done today.

**Comment by andrewdurkiewicz** [comment]
dont say 'beam of atoms' because its imply not true. Say silver. then we should add a sentence about how this works with silver because it has all of its electrons except the 5s electron paired.

**Comment by gvetaw** [comment]
The experiment works for any atom. Surprisingly it worked on hydrogen atoms as well.

**Comment by gvetaw** [comment]
That sounds like a good idea.

**Comment by andrewdurkiewicz** [comment]
wait, didnt you say it was for all atoms a second ago, im confused.

**Comment by gvetaw** [comment]
I only know it works for silver atoms because of the odd electron and hydrogen atoms in the ground state.
